services:
  db_simm:
    image: postgres:15
    container_name: simm_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_SIMM_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - simm_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_SIMM_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: simm_app
    ports:
      - "8501:8501"
    depends_on:
      db_simm:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Configuración para usar la base de datos de Docker
      - DB_SIMM_HOST=db_simm
      - DB_SIMM_PORT=5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db_simm
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  simm_data:
  pgadmin_data: